numbers = [1,2,3,4,5]
print(numbers)
print(1 in numbers)
print(len(numbers))
numbers.append(6)
print(numbers)
numbers.insert(6, 7)
print(numbers)
numbers.remove(7)
print(numbers)
numbers.clear()
print(numbers)
